# docker compose -f compose.yaml -f compose.dev.yaml up -d
version: '3.8'
services:
  python-block:
    build:
      args:
        - REQ_POSTFIX=dev
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./python-block/dev.env
    ports:
      - 8000:8000
    volumes:
      - ./python-block/app:/app
